### ISSUE TITLE
AWS access credentials

### ISSUE THREAD

**Issue by dylanramos** [CPNV-ES/trainwarehouse#3]

**Comment by NicolasGlassey** [comment]
Vous avez désormais accès à S3 avec les droits suivants.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::trainwarehouse.actualit.info",
                "arn:aws:s3:::trainwarehouse.actualit.info/*"
            ]
        }
    ]
}
